### ISSUE TITLE
Spacing of declaration blocks

### ISSUE THREAD

**Issue by eriku** [domain7/dev-wiki#6]
https://github.com/domain7/fed-wiki/blob/gh-pages/css-sass.md#spacing-of-declaration-blocks

Are we referring to whitespace (http://cssguidelin.es/#meaningful-whitespace)?

Example:

``` scss
// Bad
.something {

  .child-of-something {

    .child-of-child-of-something {
      display: none;
    } // .child-of-child-of-something
  } // .child-of-something
} // .something


.something-else {
  display: block;
} // .something-else


// Good
.something {
  .child-of-something {
    .child-of-child-of-something {
      display: none;
    } // .child-of-child-of-something
  } // .child-of-something
} // .something


.something-else {
  display: block;
} // .something-else
```

Just want to make sure that it's clear.
